/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-10-18 14:55:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1596457131000L));
    _jspx_dependants.put("jar:file:/home/hieupeo/Documents/BTAP/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/fruits/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Index</title>\n");
      out.write("<link\n");
      out.write("\thref=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css\"\n");
      out.write("\trel=\"stylesheet\" id=\"bootstrap-css\">\n");
      out.write("<script\n");
      out.write("\tsrc=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js\"></script>\n");
      out.write("<script\n");
      out.write("\tsrc=\"//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\thref=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<!-- Navigation -->\n");
      out.write("\t<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark fixed-top\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"#\">Start Bootstrap</a>\n");
      out.write("\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\n");
      out.write("\t\t\t\tdata-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\"\n");
      out.write("\t\t\t\taria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("\t\t\t\t<span class=\"navbar-toggler-icon\"></span>\n");
      out.write("\t\t\t</button>\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto\">\n");
      out.write("\t\t\t\t\t<li class=\"nav-item active\"><a class=\"nav-link\" href=\"#\">Home\n");
      out.write("\t\t\t\t\t\t\t<span class=\"sr-only\">(current)</span>\n");
      out.write("\t\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">About</a></li>\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Services</a>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href='");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("'>Login</a>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</nav>\n");
      out.write("\n");
      out.write("\t<!-- Page Content -->\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"col-lg-3\">\n");
      out.write("\n");
      out.write("\t\t\t\t<h1 class=\"my-4\">Shop Name</h1>\n");
      out.write("\t\t\t\t<div class=\"list-group\">\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"list-group-item\">Category 1</a> <a href=\"#\"\n");
      out.write("\t\t\t\t\t\tclass=\"list-group-item\">Category 2</a> <a href=\"#\"\n");
      out.write("\t\t\t\t\t\tclass=\"list-group-item\">Category 3</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- /.col-lg-3 -->\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"col-lg-9\">\n");
      out.write("\n");
      out.write("\t\t\t\t<div id=\"carouselExampleIndicators\" class=\"carousel slide my-4\"\n");
      out.write("\t\t\t\t\tdata-ride=\"carousel\">\n");
      out.write("\t\t\t\t\t<ol class=\"carousel-indicators\">\n");
      out.write("\t\t\t\t\t\t<li data-target=\"#carouselExampleIndicators\" data-slide-to=\"0\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"active\"></li>\n");
      out.write("\t\t\t\t\t\t<li data-target=\"#carouselExampleIndicators\" data-slide-to=\"1\"></li>\n");
      out.write("\t\t\t\t\t\t<li data-target=\"#carouselExampleIndicators\" data-slide-to=\"2\"></li>\n");
      out.write("\t\t\t\t\t</ol>\n");
      out.write("\t\t\t\t\t<div class=\"carousel-inner\" role=\"listbox\">\n");
      out.write("\t\t\t\t\t\t<div class=\"carousel-item active\">\n");
      out.write("\t\t\t\t\t\t\t<img class=\"d-block img-fluid\" src=\"http://placehold.it/900x350\"\n");
      out.write("\t\t\t\t\t\t\t\talt=\"First slide\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"carousel-item\">\n");
      out.write("\t\t\t\t\t\t\t<img class=\"d-block img-fluid\" src=\"http://placehold.it/900x350\"\n");
      out.write("\t\t\t\t\t\t\t\talt=\"Second slide\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"carousel-item\">\n");
      out.write("\t\t\t\t\t\t\t<img class=\"d-block img-fluid\" src=\"http://placehold.it/900x350\"\n");
      out.write("\t\t\t\t\t\t\t\talt=\"Third slide\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<a class=\"carousel-control-prev\" href=\"#carouselExampleIndicators\"\n");
      out.write("\t\t\t\t\t\trole=\"button\" data-slide=\"prev\"> <span\n");
      out.write("\t\t\t\t\t\tclass=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span> <span\n");
      out.write("\t\t\t\t\t\tclass=\"sr-only\">Previous</span>\n");
      out.write("\t\t\t\t\t</a> <a class=\"carousel-control-next\" href=\"#carouselExampleIndicators\"\n");
      out.write("\t\t\t\t\t\trole=\"button\" data-slide=\"next\"> <span\n");
      out.write("\t\t\t\t\t\tclass=\"carousel-control-next-icon\" aria-hidden=\"true\"></span> <span\n");
      out.write("\t\t\t\t\t\tclass=\"sr-only\">Next</span>\n");
      out.write("\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-4 col-md-6 mb-4\">\n");
      out.write("\t\t\t\t\t\t<div class=\"card h-100\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"><img class=\"card-img-top\"\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"http://placehold.it/700x400\" alt=\"\"></a>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">\n");
      out.write("\t\t\t\t\t\t\t\t<h4 class=\"card-title\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">Item One</a>\n");
      out.write("\t\t\t\t\t\t\t\t</h4>\n");
      out.write("\t\t\t\t\t\t\t\t<h5>$24.99</h5>\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"card-text\">Lorem ipsum dolor sit amet, consectetur\n");
      out.write("\t\t\t\t\t\t\t\t\tadipisicing elit. Amet numquam aspernatur!</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-footer\">\n");
      out.write("\t\t\t\t\t\t\t\t<small class=\"text-muted\">&#9733; &#9733; &#9733;\n");
      out.write("\t\t\t\t\t\t\t\t\t&#9733; &#9734;</small>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-4 col-md-6 mb-4\">\n");
      out.write("\t\t\t\t\t\t<div class=\"card h-100\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"><img class=\"card-img-top\"\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"http://placehold.it/700x400\" alt=\"\"></a>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">\n");
      out.write("\t\t\t\t\t\t\t\t<h4 class=\"card-title\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">Item Two</a>\n");
      out.write("\t\t\t\t\t\t\t\t</h4>\n");
      out.write("\t\t\t\t\t\t\t\t<h5>$24.99</h5>\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"card-text\">Lorem ipsum dolor sit amet, consectetur\n");
      out.write("\t\t\t\t\t\t\t\t\tadipisicing elit. Amet numquam aspernatur! Lorem ipsum dolor\n");
      out.write("\t\t\t\t\t\t\t\t\tsit amet.</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-footer\">\n");
      out.write("\t\t\t\t\t\t\t\t<small class=\"text-muted\">&#9733; &#9733; &#9733;\n");
      out.write("\t\t\t\t\t\t\t\t\t&#9733; &#9734;</small>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-4 col-md-6 mb-4\">\n");
      out.write("\t\t\t\t\t\t<div class=\"card h-100\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"><img class=\"card-img-top\"\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"http://placehold.it/700x400\" alt=\"\"></a>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">\n");
      out.write("\t\t\t\t\t\t\t\t<h4 class=\"card-title\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">Item Three</a>\n");
      out.write("\t\t\t\t\t\t\t\t</h4>\n");
      out.write("\t\t\t\t\t\t\t\t<h5>$24.99</h5>\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"card-text\">Lorem ipsum dolor sit amet, consectetur\n");
      out.write("\t\t\t\t\t\t\t\t\tadipisicing elit. Amet numquam aspernatur!</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-footer\">\n");
      out.write("\t\t\t\t\t\t\t\t<small class=\"text-muted\">&#9733; &#9733; &#9733;\n");
      out.write("\t\t\t\t\t\t\t\t\t&#9733; &#9734;</small>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-4 col-md-6 mb-4\">\n");
      out.write("\t\t\t\t\t\t<div class=\"card h-100\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"><img class=\"card-img-top\"\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"http://placehold.it/700x400\" alt=\"\"></a>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">\n");
      out.write("\t\t\t\t\t\t\t\t<h4 class=\"card-title\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">Item Four</a>\n");
      out.write("\t\t\t\t\t\t\t\t</h4>\n");
      out.write("\t\t\t\t\t\t\t\t<h5>$24.99</h5>\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"card-text\">Lorem ipsum dolor sit amet, consectetur\n");
      out.write("\t\t\t\t\t\t\t\t\tadipisicing elit. Amet numquam aspernatur!</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-footer\">\n");
      out.write("\t\t\t\t\t\t\t\t<small class=\"text-muted\">&#9733; &#9733; &#9733;\n");
      out.write("\t\t\t\t\t\t\t\t\t&#9733; &#9734;</small>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-4 col-md-6 mb-4\">\n");
      out.write("\t\t\t\t\t\t<div class=\"card h-100\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"><img class=\"card-img-top\"\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"http://placehold.it/700x400\" alt=\"\"></a>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">\n");
      out.write("\t\t\t\t\t\t\t\t<h4 class=\"card-title\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">Item Five</a>\n");
      out.write("\t\t\t\t\t\t\t\t</h4>\n");
      out.write("\t\t\t\t\t\t\t\t<h5>$24.99</h5>\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"card-text\">Lorem ipsum dolor sit amet, consectetur\n");
      out.write("\t\t\t\t\t\t\t\t\tadipisicing elit. Amet numquam aspernatur! Lorem ipsum dolor\n");
      out.write("\t\t\t\t\t\t\t\t\tsit amet.</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-footer\">\n");
      out.write("\t\t\t\t\t\t\t\t<small class=\"text-muted\">&#9733; &#9733; &#9733;\n");
      out.write("\t\t\t\t\t\t\t\t\t&#9733; &#9734;</small>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-4 col-md-6 mb-4\">\n");
      out.write("\t\t\t\t\t\t<div class=\"card h-100\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"><img class=\"card-img-top\"\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"http://placehold.it/700x400\" alt=\"\"></a>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">\n");
      out.write("\t\t\t\t\t\t\t\t<h4 class=\"card-title\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">Item Six</a>\n");
      out.write("\t\t\t\t\t\t\t\t</h4>\n");
      out.write("\t\t\t\t\t\t\t\t<h5>$24.99</h5>\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"card-text\">Lorem ipsum dolor sit amet, consectetur\n");
      out.write("\t\t\t\t\t\t\t\t\tadipisicing elit. Amet numquam aspernatur!</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-footer\">\n");
      out.write("\t\t\t\t\t\t\t\t<small class=\"text-muted\">&#9733; &#9733; &#9733;\n");
      out.write("\t\t\t\t\t\t\t\t\t&#9733; &#9734;</small>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!-- /.row -->\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- /.col-lg-9 -->\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- /.row -->\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\t<!-- /.container -->\n");
      out.write("\n");
      out.write("\t<!-- Footer -->\n");
      out.write("\t<footer class=\"py-5 bg-dark\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<p class=\"m-0 text-center text-white\">Copyright &copy; Your\n");
      out.write("\t\t\t\tWebsite 2020</p>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- /.container -->\n");
      out.write("\t</footer>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /views/index.jsp(17,7) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/css/index.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /views/index.jsp(38,52) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/login");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }
}
